package provision

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/RainerGewalt/TrailMQ/internal/layout"
)

// OverrideFileName is the generated Compose override that redirects the
// recipe's bind mounts at the user's state directory.
const OverrideFileName = "compose.override.yaml"

// stateMounts maps a container path to the state directory that must appear
// there when state does not sit beside the Compose file.
//
// Only the writable mounts are redirected. config.yaml and nginx.conf are
// product assets: they ship with the installation, are read-only, and stay
// where the recipe puts them.
func stateMounts(r layout.Recipe) [][2]string {
	return [][2]string{
		{r.DataDir(), "/app/data"},
		{r.LogsDir(), "/app/logs"},
		{r.AuditDir(), "/app/audit-archive"},
		{r.CertsDir(), "/app/certs:ro"},
		{r.SecretsDir(), "/app/secrets:ro"},
	}
}

// EnsureComposeOverride writes the override for an installed layout and
// returns its path. It returns an empty path when the layout needs none.
//
// The recipe's Compose file mounts ./data, ./certs and ./secrets relative to
// itself, which is correct for a folder the user owns and wrong for an
// installation whose program directory must stay read-only. Rather than
// shipping two Compose files that could drift, the launcher generates an
// override next to the state it points at. Compose merges volumes by their
// container path, so each entry here replaces the recipe's relative one
// instead of being mounted twice.
func EnsureComposeOverride(l layout.Layout, r layout.Recipe) (string, error) {
	if !l.Separated() {
		return "", nil
	}

	if err := os.MkdirAll(r.State, 0o755); err != nil {
		return "", err
	}

	var b strings.Builder
	b.WriteString("# Generated by the TrailMQ launcher — do not edit.\n")
	b.WriteString("#\n")
	b.WriteString("# This installation keeps product assets and your data apart. The recipe's\n")
	b.WriteString("# Compose file mounts its own folder; these entries point the writable\n")
	b.WriteString("# mounts at your state directory instead.\n")
	b.WriteString("#\n")
	b.WriteString("# It is rewritten on every start, so editing it has no lasting effect.\n")
	b.WriteString("\nservices:\n  backend:\n    volumes:\n")

	for _, mount := range stateMounts(r) {
		source, target := mount[0], mount[1]
		// Compose accepts forward slashes on every platform; a Windows path
		// with backslashes would be read as an escape inside a YAML scalar.
		b.WriteString(fmt.Sprintf("      - %q\n", filepath.ToSlash(source)+":"+target))
	}

	path := filepath.Join(r.State, OverrideFileName)
	if err := os.WriteFile(path, []byte(b.String()), 0o644); err != nil {
		return "", fmt.Errorf("could not write the Compose override: %w", err)
	}
	return path, nil
}
